FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# VaR Calculator 

API that allows clients to create, read, update and delete portfolios

## Portfolios Collection [/portfolios]

### List All Portfolios [GET]

+ Request (application/json)

+ Response 200 (application/json)

        [
                "data": {
                    "id": 32767,
                    "name": "Chris1"
                }, 
                "data": {
                    "id": 32765,
                    "name": "Chris2"
                }
        ]

### Create a portfolio [POST]

+ Request (application/json)

        {
                "data": {
                    "name": "Chris1"
                }
        }

+ Response 201 (application/json)

    + Body

            {
                "data": {
                    "id": 1234,
                    "name": "Chris1"
                }
            }
            

## Portfolio Instance [/portfolios/{portfolio_id}]

### Get Portfolio [GET]

+ Parameters
    + portfolio_id: 1 (required, number) - Unique portfolio id as a long

+ Request (application/json)

+ Response 201 (application/json)

        {
                "data": {
                    "name": "Chris1"
                    "id": 1234
                }
        }
        
+ Response 404 (application/json)
    
### Delete Portfolio [DELETE]

+ Parameters
    + portfolio_id: 12345 (required, number) - Unique portfolio id as a long

+ Request (application/json)

+ Response 201 (application/json)

+ Response 404 (application/json)

## Portfolio VaR [/portfolios/{portfolio_id}/var/{&var_percentile}{&var_days}]

### Get Portfolio VaR [GET]

+ Parameters
    + portfolio_id: 12345 (required, number) - Unique portfolio id as a long
    + var_percentile: 0.90 (optional, number) - VaR percentile
        + default: 0.95
    + var_days: 1 (optional, number) - number of days
        + default: 1

+ Request (application/json)

+ Response 201 (application/json)

        {
                "data": {
                    "var": 1245
                }
        }

+ Response 404 (application/json)

## Portfolio Vol [/portfolios/{portfolio_id}/vol]

### Get Portfolio Vol [GET]

+ Parameters
    + portfolio_id: 12345 (required, number) - Unique portfolio id as a long

+ Request (application/json)

+ Response 201 (application/json)

        {
                "data": {
                    "vol": 0.01
                }
        }

+ Response 404 (application/json)

## Portfolio Net Market Value [/portfolios/{portfolio_id}/nmv]

### Get Portfolio NMV [GET]

+ Parameters
    + portfolio_id: 12345 (required, number) - Unique portfolio id as a long

+ Request (application/json)

+ Response 201 (application/json)

        {
                "data": {
                    "nmv": 10000
                }
        }

+ Response 404 (application/json)

## Positions [/portfolios/{portfolio_id}/positions]

### Get positions [GET]

+ Parameters
    + portfolio_id: 12345 (required, number) - Unique portfolio id as a long

+ Request (application/json)

+ Response 201 (application/json)

        [ 
            "data": { "side": LONG, "symbol": "IBM", "quantity": 100 }, 
            "data": { "side": SHORT  "symbol": "MSFT", "quantity": -100 }, 
            "data": { "side": LONG, "symbol": "MS", "quantity": 200 }, 
            "data": { "side": LONG, "symbol": "DUK", "quantity": 100 }, 
        ]


+ Response 404 (application/json)

### Create one a position as part of portfolio [POST]

+ Parameters
    + portfolio_id: 12345 (required, number) - Unique portfolio id as a long

+ Request (application/json)

        {
                "data": { 
                    "symbol": "IBM", "quantity": 100 
                }
        }

+ Response 201 (application/json)

        {
                "data": { 
                    "side": LONG, "symbol": "IBM", "quantity": 100 
                } 
                    
        }

+ Response 404 (application/json)

## Specific positions [/portfolios/{portfolio_id}/positions/{position_id}]

### Update specific position [POST]

+ Request (application/json)

        {
                "data": {
                    "quantity": 500 
                }
        }
        
+ Response 201 (application/json)

+ Response 404 (application/json)

### Delete specific position [DELETE]

+ Request (application/json)

+ Response 201 (application/json)

+ Response 404 (application/json)
